#!/usr/bin/env python3
"""
function that inserts a new document in a collection based on kwargs
Method: def insert_school(mongo_collection, **kwargs)
Return: new_id
"""
import pymongo


def insert_school(mongo_collection, **kwargs):
    """
    return: new_id -> inserted_id: attribute generated by insertOne()
        is used to access the _id of the newly inserted document
    """
    if mongo_collection is None:
        return None
    result = mongo_collection.insert_one(kwargs)
    return result.inserted_id
